# Generated by Django 6.0.5 on 2026-06-16 02:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vintasend_django",
            "0002_notification_email_or_phone_notification_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="adapter_extra_parameters",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="extra parameters for the notification adapter",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="context_kwargs",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="context_used",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="context used when notification was sent",
            ),
        ),
    ]
