# Generated by Django 6.0.5 on 2026-07-23 15:43

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vintasend_django",
            "0003_alter_notification_adapter_extra_parameters_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="git_commit_sha",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="git commit sha"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="read at"),
        ),
        migrations.AddField(
            model_name="notification",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
        ),
        migrations.AddField(
            model_name="notification",
            name="tenant",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="tenant",
            ),
        ),
        migrations.CreateModel(
            name="AttachmentFileRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "checksum",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "storage_identifiers",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "indexes": [
                    models.Index(
                        fields=["checksum", "size"],
                        name="vintasend_d_checksu_db6cdf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_inline", models.BooleanField(default=False)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_attachments",
                        to="vintasend_django.attachmentfilerecord",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="vintasend_django.notification",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        # NOTE: the old ``Attachment`` model is intentionally NOT deleted here. Deleting it is
        # deferred to migration 0006, after 0005 copies any existing attachment rows into the
        # new ``AttachmentFileRecord`` / ``NotificationAttachment`` tables. This migration is
        # purely additive so no attachment data is lost on upgrade.
    ]
