# Generated by Django 6.0.7 on 2026-08-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vintasend_django", "0006_delete_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="requested_template_version",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="requested template version"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="used_template_version",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="used template version"
            ),
        ),
    ]
